### ISSUE TITLE
Pool connecting freezes 

### ISSUE THREAD

**Issue by Sor3nt** [NMminer1024/NMMiner#1]
I use the latest Version v0.2.10 with the default Pool Server, just changed the BTC Address.

What happens ?

When i turn on the device, the Msg say "Wifi Connected" and then "Pool connecting..." after 1-2 seconds, the device reboots and freeze again with the "Pool connecting..." message.

(Happens with and without SSL)

It worked fine with the old firmware v0.1.54.

**Comment by Sor3nt** [comment]
solved, i need to reset the device with these https://github.com/NMminer1024/NMMiner?tab=readme-ov-file#solutions

**Comment by NMminer1024** [comment]
Happy to hear that
