### ISSUE TITLE
Miner lottery chain?

### ISSUE THREAD

**Issue by dwightmulcahy** [NMminer1024/NMMiner#10]
"Multiple usb-chains can be connected in series to form a lottery chain"

This was mentioned in the latest email sent.  How do we enable this if we use multiple devices?

**Comment by NMminer1024** [comment]
![1732723740561](https://github.com/user-attachments/assets/94945d3a-aca8-40cd-ad31-c01ed5a5ca6e)
Something like this，NM official board，
https://www.aliexpress.com/item/3256807909937814.html?gatewayAdapt=4itemAdapt

**Comment by NMminer1024** [comment]
> "Multiple usb-chains can be connected in series to form a lottery chain"
> 
> This was mentioned in the latest email sent. How do we enable this if we use multiple devices?

![image](https://github.com/user-attachments/assets/a10a5137-e362-40a8-b0da-b93fbbafedf2)

Something like this，NM official board，
https://www.aliexpress.com/item/3256807909937814.html?gatewayAdapt=4itemAdapt

**Comment by dwightmulcahy** [comment]
Ahhh, so specific to those and not something available to other boards.  I have 8 of mine Lyligo-display-S3's running on an OctaMiner but it is just providing power to all of those as they appear individually in the mining pool.  It would be nice if  they mined as one.

**Comment by NMminer1024** [comment]
> Ahhh, so specific to those and not something available to other boards. I have 8 of mine Lyligo-display-S3's running on an OctaMiner but it is just providing power to all of those as they appear individually in the mining pool. It would be nice if they mined as one.

Yes，We solved the issue you mentioned days ago，need your feedback of the testing

**Comment by dwightmulcahy** [comment]
I posted that it works great in #9 ...

![PXL_20241126_234207524](https://github.com/user-attachments/assets/519205fd-5e61-4355-8dec-fe23e3c526b7)

**Comment by NMminer1024** [comment]
> I posted that it works great in #9 ...
> 
> ![PXL_20241126_234207524](https://private-user-images.githubusercontent.com/8507802/390631018-519205fd-5e61-4355-8dec-fe23e3c526b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Njc2MTEsIm5iZiI6MTczMjc2NzMxMSwicGF0aCI6Ii84NTA3ODAyLzM5MDYzMTAxOC01MTkyMDVmZC01ZTYxLTQzNTUtOGRlYy1mZTIzZTNjNTI2YjcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMDQxNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhmYmQzZDM3Yzc3YzMxY2ZkODBkMTRjNDZjMDc4ZjQ2OGJjNzMzNzcyNTVhNTE3MGZjM2U2NGQ5ODk5MzJlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wdsgrrFehnmmf6nxiOeJ4SOzWX9pI05AQL8sF0DxCPg)

Sorry ，haven't noticed before，Nice board
