### ISSUE TITLE
Ladebildschirm t190

### ISSUE THREAD

**Issue by Daniloquake** [NMminer1024/NMMiner#3]
Hallo 
der T190 zeigt nur den Ladebildschirm an und es kommt kein AP Wlan.
v0.3.01 ist installiert.
danke für ihre hilfe

**Comment by NMminer1024** [comment]
Did you connect the pool? pool seems crashed yesterday

**Comment by Daniloquake** [comment]
it works now.--Gesendet mit der GMX Mail AppAm 08.09.24, 15:12 schrieb NMtech ***@***.***>:

  
  
   Hallo der T190 zeigt nur den Ladebildschirm an und es kommt kein AP Wlan. v0.3.01 ist installiert. danke für ihre hilfe
  
  Did you connect the pool? pool seems crashed yesterday
