### ISSUE TITLE
FW_update.exe Error

### ISSUE THREAD

**Issue by molachai77** [NMminer1024/NMMiner#4]
Attempted to update to the latest firmware and received the error shown in the attached picture. It stops and does not go further than the wrror. Seems like 2 letters just got reversed and is making it error out.
![FW Flasher Error](https://github.com/user-attachments/assets/6d376c5a-15ea-4af2-9cd6-d0759049974b)

**Comment by NMminer1024** [comment]
Seems that COM port haven't mount yet，just have a look about it

**Comment by molachai77** [comment]
Com Port is good since I can read the device and do other things using it. Even after this error is given. So mounting is not an issue. :)

**Comment by molachai77** [comment]
Well I flashed the firmware using the Meshtastic web flasher and the firmware .bin file from you. So all good now! Was never able to get your fw_update.exe to work no matter what I did. So if others have an issue, they can use a web flasher like I did to perform the firmware update. Thanks!

**Comment by molachai77** [comment]
Found work around with a web flasher for meshtastic. But the fw_update.exe still needs updated so it will work properly. Thanks for making this!

**Comment by NMminer1024** [comment]
> Found work around with a web flasher for meshtastic. But the fw_update.exe still needs updated so it will work properly. Thanks for making this!

OK，we will keep working for this

**Comment by betterpony** [comment]
> Well I flashed the firmware using the Meshtastic web flasher and the firmware .bin file from you. So all good now! Was never able to get your fw_update.exe to work no matter what I did. So if others have an issue, they can use a web flasher like I did to perform the firmware update. Thanks!

Hi，We update the web flash tool now，thanks

**Comment by NMminer1024** [comment]
> Found work around with a web flasher for meshtastic. But the fw_update.exe still needs updated so it will work properly. Thanks for making this!

Hi，we update the web flash tool now，thanks your feedback.
