### ISSUE TITLE
Mqtt possible 

### ISSUE THREAD

**Issue by Bluelightcrew** [NMminer1024/NMMiner#8]
Is it possible to integrate an mqtt interface so that you can, for example, access the data in the smart home

**Comment by NMminer1024** [comment]
> Yes, but mqtt will consume a certain amount of CPU resources, so the hashrate will be affected to a certain extent and decrease.
> So，what's the origin demands to connect to smart home system?

Yes, but mqtt will consume a certain amount of CPU resources, so the hashrate will be affected to a certain extent and decrease.
So，what's the origin demands to connect to smart home system?

**Comment by Bluelightcrew** [comment]
Ok I understand, hashrate is more important. Thanks for the answer. I will se if I can pars it from the server page

**Comment by Bluelightcrew** [comment]
Is it possible to flash it on a ESP32-2432S028R? I like this Firmware more with this web monitor!

**Comment by NMminer1024** [comment]
> Is it possible to flash it on a ESP32-2432S028R? I like this Firmware more with this web monitor!

Sure ，https://flash.nmminer.com/  here you can flash it by yourself Sir.
![image](https://github.com/user-attachments/assets/2d183b7c-2adc-4ea0-b3ba-435ec7a414a7)

**Comment by NMminer1024** [comment]
> Ok I understand, hashrate is more important. Thanks for the answer. I will se if I can pars it from the server page

https://github.com/NMminer1024/NMController_web
Here is a reference for Web monitor ，hope that's a useful example for you.
