### ISSUE TITLE
NMMiner use on OctoMiner

### ISSUE THREAD

**Issue by dwightmulcahy** [NMminer1024/NMMiner#9]
I have an OctoMiner (https://www.tindie.com/products/morpheans/octominer-operate-up-to-8-nerdminers/) with 8 Lilygo T Display-S3's that I have been running NerdminerV2 on it for a while.   The weak point of the OctoMiner is the main USB-C connector that would break off if you sneezed on it (and I did), but I looked at the traces. The 5V pins were all connected, so I tried powering one of the Lilygo T Display-S3 with its USB-C, and it powered all eight units from it without issue with a 5amp USB power supply.  I have been running like this for at least six months.

I decided to switch over to NMMiner for the extra hash rate and flashed all of my Lilygo T Display-S3's... now when I plug in just one it only powers the single unit.  

Does NMMiner disable the 5V Power Pins?  What gives?

**Comment by dwightmulcahy** [comment]
<sigh>

So I checked all the pins on the OctoMiner, and all are getting 5V power.   I had a couple of Nerdminers that I popped in, along with a couple of NMMiners.  No matter which one of the NMMiners I power, the Nerdminer comes up along with the single-powered NMMiner.  Tried different USB-C power blocks from 4amp to a 96W Apple power brick, still the same.

I did try individually powering the NMMiners and that worked, but disappointing since the OctoMiner should only have to be powered off of a singly USB-C power supply.  

Seems that the NMMiners wouldn't boot up set up on the OctoMiner like this.

**Comment by NMminer1024** [comment]
> So I checked all the pins on the OctoMiner, and all are getting 5V power. I had a couple of Nerdminers that I popped in, along with a couple of NMMiners. No matter which one of the NMMiners I power, the Nerdminer comes up along with the single-powered NMMiner. Tried different USB-C power blocks from 4amp to a 96W Apple power brick, still the same.
> 
> I did try individually powering the NMMiners and that worked, but disappointing since the OctoMiner should only have to be powered off of a singly USB-C power supply.
> 
> Seems that the NMMiners wouldn't boot up set up on the OctoMiner like this.

Thanks your feedback Sir，could you please join the support channel https://t.me/NMMiner，and give us more details

**Comment by NMminer1024** [comment]
> So I checked all the pins on the OctoMiner, and all are getting 5V power. I had a couple of Nerdminers that I popped in, along with a couple of NMMiners. No matter which one of the NMMiners I power, the Nerdminer comes up along with the single-powered NMMiner. Tried different USB-C power blocks from 4amp to a 96W Apple power brick, still the same.
> 
> I did try individually powering the NMMiners and that worked, but disappointing since the OctoMiner should only have to be powered off of a singly USB-C power supply.
> 
> Seems that the NMMiners wouldn't boot up set up on the OctoMiner like this.

Thanks your feedback Sir，could you please join the support channel and give us more details ： https://t.me/NMMiner

**Comment by NMminer1024** [comment]
> So I checked all the pins on the OctoMiner, and all are getting 5V power. I had a couple of Nerdminers that I popped in, along with a couple of NMMiners. No matter which one of the NMMiners I power, the Nerdminer comes up along with the single-powered NMMiner. Tried different USB-C power blocks from 4amp to a 96W Apple power brick, still the same.
> 
> I did try individually powering the NMMiners and that worked, but disappointing since the OctoMiner should only have to be powered off of a singly USB-C power supply.
> 
> Seems that the NMMiners wouldn't boot up set up on the OctoMiner like this.

![image](https://github.com/user-attachments/assets/bc36390e-1161-4f77-a1a8-49ac445d67ab)
Did you have any details of this board？

**Comment by NMminer1024** [comment]
![image](https://github.com/user-attachments/assets/2d81a480-cba5-4804-8e09-4e62c46b672e)
I review the schematic ，something should be noticed here , so we will update in next update，could you please do us a test in beta version.

**Comment by NMminer1024** [comment]
![image](https://github.com/user-attachments/assets/22dfa14b-11d9-45a0-a6fd-bd68c7a47918)

Thanks your feed，I think we have solved this issues，update in v0.5.01

**Comment by dwightmulcahy** [comment]
Awesome.  If you have firmware you want me to test, lmk.

**Comment by NMminer1024** [comment]
> Awesome. If you have firmware you want me to test, lmk.

https://debug.nmminer.com:5004/

V0.5.01

**Comment by NMminer1024** [comment]
Hi Sir，
    Have you ever update the latest firmware(v0.5.01)? Did the issue of
Lilygo T display s3 you mentioned fixed？you are so kind if you can give any
feedback，thanks！

**Comment by NMminer1024** [comment]
> I have an OctoMiner (https://www.tindie.com/products/morpheans/octominer-operate-up-to-8-nerdminers/) with 8 Lilygo T Display-S3's that I have been running NerdminerV2 on it for a while. The weak point of the OctoMiner is the main USB-C connector that would break off if you sneezed on it (and I did), but I looked at the traces. The 5V pins were all connected, so I tried powering one of the Lilygo T Display-S3 with its USB-C, and it powered all eight units from it without issue with a 5amp USB power supply. I have been running like this for at least six months.
> 
> I decided to switch over to NMMiner for the extra hash rate and flashed all of my Lilygo T Display-S3's... now when I plug in just one it only powers the single unit.
> 
> Does NMMiner disable the 5V Power Pins? What gives?

Hi Sir，
    Have you ever update the latest firmware(v0.5.01)? Did the issue of
Lilygo T display s3 you mentioned fixed？you are so kind if you can give any
feedback，thanks！

**Comment by dwightmulcahy** [comment]
Hi, I'm traveling and won't be able to try till 11/26... I'll post the results then.

**Comment by dwightmulcahy** [comment]
Works nicely now!  Thanks for the quick resolution.

![PXL_20241126_234207524](https://github.com/user-attachments/assets/ec450d1b-de67-4504-b720-829f69a7226c)

**Comment by dwightmulcahy** [comment]
Thanks!
